# Created using winget create
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: alvarofraguas.EdrShield
PackageVersion: 1.1.0
InstallerType: portable
Commands:
  - edrshield
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/alvarofraguas/EdrShield/releases/download/v1.1.0/edrshield_signed.exe
    InstallerSha256: 8385C5456CB2DFDE49464FC5DAD2182349FF47D9A1B011C4CA2FFD9FCCB4854B
ManifestType: installer
ManifestVersion: 1.6.0
